#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : uchardet
Version  : 0.0.6
Release  : 1
URL      : https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.6.tar.xz
Source0  : https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.6.tar.xz
Summary  : An encoding detector library ported from Mozilla
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1 MPL-1.1
Requires: uchardet-bin = %{version}-%{release}
Requires: uchardet-lib = %{version}-%{release}
Requires: uchardet-man = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
# Supporting new or Updating languages #
We generate statistical language data using Wikipedia as natural
language text resource.

%package bin
Summary: bin components for the uchardet package.
Group: Binaries

%description bin
bin components for the uchardet package.


%package dev
Summary: dev components for the uchardet package.
Group: Development
Requires: uchardet-lib = %{version}-%{release}
Requires: uchardet-bin = %{version}-%{release}
Provides: uchardet-devel = %{version}-%{release}
Requires: uchardet = %{version}-%{release}

%description dev
dev components for the uchardet package.


%package lib
Summary: lib components for the uchardet package.
Group: Libraries

%description lib
lib components for the uchardet package.


%package man
Summary: man components for the uchardet package.
Group: Default

%description man
man components for the uchardet package.


%prep
%setup -q -n uchardet-0.0.6
cd %{_builddir}/uchardet-0.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1585786505
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}  VERBOSE=1
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1585786505
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/uchardet

%files dev
%defattr(-,root,root,-)
/usr/include/uchardet/uchardet.h
/usr/lib64/libuchardet.so
/usr/lib64/pkgconfig/uchardet.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libuchardet.so.0
/usr/lib64/libuchardet.so.0.0.6

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/uchardet.1
